clear

filenames = {'P1_Renato.mat', 'P1_Sergio.mat', ... 
    'P2_Renato.mat', 'P2_Sergio.mat', ...
    'P3_Renato.mat', 'P3_Sergio.mat', ...
    'P4_Renato.mat', 'P4_Sergio.mat', ...
    'P5_Renato.mat', 'P5_Sergio.mat'};

for i = 1:numel(filenames)
    load(filenames{i});
end

%concatenar todos os numeros
numbers = [P1_Renato, P1_Sergio, ...
    P2_Renato, P2_Sergio, ...
    P3_Renato, P3_Sergio, ...
    P4_Renato, P4_Sergio, ...
    P5_Renato, P5_Sergio];

save('numbers.mat', 'numbers');