load('P1_Renato.mat')% , 'P1_Sergio.mat', 'P2_Renato.mat', 'P2_Sergio.mat', ...
    %'P3_Renato.mat', 'P3_Sergio.mat', 'P4_Renato.mat', 'P4_Sergio.mat', ...
    %'P5_Renato.mat', 'P5_Sergio.mat', 'P6_Renato.mat', 'P6_Sergio.mat', ...
    %'P7_Renato.mat', 'P7_Sergio.mat', 'P8_Renato.mat', 'P8_Sergio.mat', ...
    %'P9_Renato.mat', 'P9_Sergio.mat', 'P10_Renato.mat', 'P10_Sergio.mat')

%concatenar todos os numeros
numbers = [P1_Renato , P1_Sergio, P2_Renato, P2_Sergio, ...
    P3_Renato, P3_Sergio, P4_Renato, P4_Sergio, P5_Renato, P5_Sergio, ...
    P6_Renato, P6_Sergio, P7_Renato, P7_Sergio, P8_Renato, P8_Sergio, ...
    P9_Renato, P9_Sergio, P10_Renato, P10_Sergio]